#!/usr/bin/env bash
#
# Run once after cloning
# macOS and Linux compatible, idempotent, colored line-level output
# Automatically sets up pre-commit hook
# Supports Husky, pre-commit, lefthook, and custom hooks
# For codebase-level hooks (Husky), creates a PR with the changes

set -Eeuo pipefail

# Create secure temporary directory and ensure cleanup on exit
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

# Store the original working directory (absolute path)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKING_DIR="$(pwd)"

# ---------- Colors ----------
RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
MAGENTA='\033[1;35m'
CYAN='\033[1;36m'
RESET='\033[0m'

fail() {
  echo -e "${RED}❌ SETUP FAILED${RESET}"
  echo -e "${RED}$1${RESET}"
  exit 1
}

info() {
  echo -e "${BLUE}ℹ $1${RESET}"
}

warn() {
  echo -e "${YELLOW}⚠ $1${RESET}"
}

success() {
  echo -e "${GREEN}✔ $1${RESET}"
}

debug() {
  echo -e "${CYAN}🔍 $1${RESET}"
}

# ---------- Configuration ----------
BRANCH_PREFIX="security/add-gitleaks-pre-commit-hook"
PR_TITLE="Add Gitleaks secret scanning to pre-commit hook"
PR_BODY="## Summary
This PR adds Gitleaks secret scanning to the pre-commit hook.

### What's included:
- Gitleaks binary installation in \`.gitleaks/bin/\`
- Pre-commit hook integration for automatic secret scanning on every commit
- Automatic blocking of commits containing detected secrets

### How it works:
1. On every commit, Gitleaks scans staged files for secrets
2. If secrets are detected, the commit is blocked with detailed output
3. Developers must remove or rotate secrets before committing

### Files modified:
- \`.husky/pre-commit\` - Added Gitleaks scanning logic

---
*This PR was automatically generated by the security pre-commit hook setup script.*"

echo -e "${YELLOW}⚡ Setting up STRICT MODE pre-commit hook...${RESET}"

# ---------- Check if we're in a git repository ----------
if [ ! -d ".git" ]; then
  fail "Not a git repository. Please run this script from the root of a git repository."
fi
info "Git repository detected"

# ---------- Platform ----------
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "$OS" in
  darwin) OS="darwin" ;;
  linux) OS="linux" ;;
  *) fail "Unsupported operating system: $OS (only darwin and linux are supported)" ;;
esac
info "Detected OS: $OS"

ARCH="$(uname -m)"
case "$ARCH" in
  x86_64|amd64) ARCH="amd64" ;;
  arm64|aarch64) ARCH="arm64" ;;
  *) fail "Unsupported architecture: $ARCH" ;;
esac
info "Detected architecture: $ARCH"

# ---------- Paths ----------
GITLEAKS_BIN_DIR=".gitleaks/bin"
GITLEAKS_BIN="$GITLEAKS_BIN_DIR/gitleaks"
VERSION_FILE="$GITLEAKS_BIN_DIR/VERSION"
GIT_HOOK_FILE=".git/hooks/pre-commit"
HUSKY_HOOK_FILE=".husky/pre-commit"

# Gitleaks section markers for idempotent appending
GITLEAKS_START_MARKER="# >>>>>> GITLEAKS SECRET SCAN - DO NOT REMOVE >>>>>>"
GITLEAKS_END_MARKER="# <<<<<< GITLEAKS SECRET SCAN - DO NOT REMOVE <<<<<<"

# Track if we need to create a PR
NEEDS_PR=false
HOOK_MODIFIED=false
PR_CREATED=false

mkdir -p "$GITLEAKS_BIN_DIR" ".git/hooks"

# ---------- Check if hook is codebase-level (committed to repo) ----------
is_codebase_level_hook() {
  local system="$1"
  case "$system" in
    husky|husky-no-hook)
      # Husky v5+ stores hooks in .husky/ which is committed
      return 0
      ;;
    *)
      # All other systems use .git/hooks/ which is not committed
      return 1
      ;;
  esac
}

# ---------- Get default branch ----------
get_default_branch() {
  # Try to get the default branch from remote
  local default_branch=""
  default_branch=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@') || true
  
  if [ -z "$default_branch" ]; then
    # Fallback: try common default branch names
    if git show-ref --verify --quiet refs/remotes/origin/main 2>/dev/null; then
      default_branch="main"
    elif git show-ref --verify --quiet refs/remotes/origin/master 2>/dev/null; then
      default_branch="master"
    else
      # Last resort: use current branch
      default_branch=$(git branch --show-current 2>/dev/null || echo "main")
    fi
  fi
  
  echo "$default_branch"
}

# ---------- Check if GitHub CLI is available ----------
check_gh_cli() {
  if command -v gh &>/dev/null; then
    # Check if authenticated
    if gh auth status &>/dev/null; then
      return 0
    else
      warn "GitHub CLI (gh) is installed but not authenticated"
      warn "Run 'gh auth login' to authenticate for automatic PR creation"
      return 1
    fi
  else
    warn "GitHub CLI (gh) not found. PR will not be created automatically"
    warn "Install gh CLI: https://cli.github.com/"
    return 1
  fi
}

# ---------- Test pre-commit hook execution ----------
test_hook_execution() {
  local hook_file="$1"
  
  echo ""
  echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  echo -e "${CYAN}  Testing Pre-commit Hook Execution${RESET}"
  echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  
  if [ ! -f "$hook_file" ]; then
    warn "Hook file does not exist: $hook_file"
    return 1
  fi
  
  if [ ! -x "$hook_file" ]; then
    debug "Making hook file executable: $hook_file"
    chmod +x "$hook_file"
  fi
  
  info "Testing hook syntax..."
  
  # Check if the hook is a valid shell script
  local shell_type=""
  shell_type=$(head -1 "$hook_file" | sed 's/^#![[:space:]]*//' || echo "")
  
  if [[ "$shell_type" == *"bash"* ]]; then
    debug "Hook uses bash, running syntax check..."
    if ! bash -n "$hook_file" 2>&1; then
      echo -e "${RED}❌ Hook syntax check failed (bash)${RESET}"
      return 1
    fi
    success "Bash syntax check passed"
  elif [[ "$shell_type" == *"sh"* ]]; then
    debug "Hook uses sh, running syntax check..."
    # sh -n might not catch all issues, but it's a basic check
    if ! sh -n "$hook_file" 2>&1; then
      echo -e "${RED}❌ Hook syntax check failed (sh)${RESET}"
      return 1
    fi
    success "Shell syntax check passed"
  else
    debug "Unknown shell type: $shell_type, skipping detailed syntax check"
    # Try bash as fallback
    if bash -n "$hook_file" 2>/dev/null; then
      success "Basic syntax check passed"
    else
      warn "Could not validate hook syntax, proceeding with caution"
    fi
  fi
  
  # Test execution in a dry-run manner
  info "Testing hook execution (dry run)..."
  
  # Create a simple test: source the hook in a subshell with set -n (syntax check)
  local test_result=0
  
  # For Husky hooks, we need to mock the husky.sh sourcing
  if grep -q "husky.sh" "$hook_file" 2>/dev/null; then
    debug "Husky hook detected, testing with mocked husky.sh..."
    
    # Create a temporary mock husky.sh
    local mock_husky_dir="$TMP_DIR/husky_mock/_"
    mkdir -p "$mock_husky_dir"
    echo '#!/bin/sh' > "$mock_husky_dir/husky.sh"
    echo '# Mock husky.sh for testing' >> "$mock_husky_dir/husky.sh"
    
    # Test the hook with mocked husky - use absolute path
    local abs_hook_file
    abs_hook_file="$WORKING_DIR/$hook_file"
    
    (
      cd "$TMP_DIR/husky_mock" || exit 1
      # Copy the hook
      cp "$abs_hook_file" ./pre-commit-test 2>/dev/null || exit 1
      chmod +x ./pre-commit-test
      
      # Try to parse/validate (not execute)
      if head -1 ./pre-commit-test | grep -q bash; then
        bash -n ./pre-commit-test 2>&1
      else
        sh -n ./pre-commit-test 2>&1
      fi
    ) || test_result=1
  else
    # Direct syntax validation
    (
      if head -1 "$hook_file" 2>/dev/null | grep -q bash; then
        bash -n "$hook_file" 2>&1
      else
        sh -n "$hook_file" 2>&1
      fi
    ) || test_result=1
  fi
  
  if [ "$test_result" -ne 0 ]; then
    echo -e "${RED}❌ Hook execution test failed${RESET}"
    return 1
  fi
  success "Hook execution test passed"
  
  # Verify Gitleaks binary is accessible (important for the hook to work)
  info "Verifying Gitleaks binary is accessible..."
  if [ ! -x "$GITLEAKS_BIN" ]; then
    echo -e "${RED}❌ Gitleaks binary not found or not executable at $GITLEAKS_BIN${RESET}"
    return 1
  fi
  success "Gitleaks binary is accessible"
  
  # Run a quick Gitleaks test to ensure it works
  info "Running Gitleaks validation test..."
  if ! "$GITLEAKS_BIN" version >/dev/null 2>&1; then
    echo -e "${RED}❌ Gitleaks binary validation failed${RESET}"
    return 1
  fi
  success "Gitleaks binary validation passed"
  
  echo ""
  success "Pre-commit hook validation completed successfully!"
  return 0
}

# ---------- Rollback function for PR workflow ----------
# Defined at top level so it can access all necessary variables
_pr_rollback() {
  local orig_branch="$1"
  local new_branch="$2"
  local default_branch="$3"
  local stash_restore="$4"
  
  echo ""
  warn "Rolling back changes due to failure..."
  
  # Switch back to original branch
  if [ -n "$orig_branch" ]; then
    debug "Switching back to original branch: $orig_branch"
    git checkout "$orig_branch" 2>/dev/null || git checkout "$default_branch" 2>/dev/null || true
  fi
  
  # Delete the new branch if it was created
  if [ -n "$new_branch" ] && git show-ref --verify --quiet "refs/heads/$new_branch" 2>/dev/null; then
    debug "Deleting failed branch: $new_branch"
    git branch -D "$new_branch" 2>/dev/null || true
  fi
  
  # Restore stashed changes
  if [ "$stash_restore" = "true" ]; then
    debug "Restoring stashed changes..."
    git stash pop 2>/dev/null || warn "Could not restore stashed changes. Use 'git stash list' to find them."
  fi
  
  warn "Rollback complete. Please check your repository state."
}

# ---------- Create branch, commit, push, and PR ----------
create_pr_for_hook_change() {
  local hook_file="$1"
  local original_branch=""
  local new_branch=""
  local default_branch=""
  local stash_needed="false"
  
  echo ""
  echo -e "${MAGENTA}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  echo -e "${MAGENTA}  Creating PR for Codebase-Level Hook${RESET}"
  echo -e "${MAGENTA}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
  
  # Get current branch and default branch
  original_branch=$(git branch --show-current 2>/dev/null || echo "")
  if [ -z "$original_branch" ]; then
    warn "Could not determine current branch (detached HEAD?)"
    original_branch="HEAD"
  fi
  
  default_branch=$(get_default_branch)
  
  info "Current branch: $original_branch"
  info "Default branch: $default_branch"
  
  # Generate unique branch name with timestamp
  local timestamp
  timestamp=$(date +%Y%m%d_%H%M%S)
  new_branch="${BRANCH_PREFIX}-${timestamp}"
  
  # Check if there are uncommitted changes
  if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
    local changed_files=""
    changed_files=$(git diff --name-only 2>/dev/null || echo "")
    changed_files="${changed_files}$(git diff --cached --name-only 2>/dev/null || echo "")"
    
    if [ -n "$changed_files" ]; then
      stash_needed="true"
      info "Stashing existing changes before branch operations..."
      if ! git stash push -m "Auto-stash before gitleaks hook setup" --include-untracked 2>/dev/null; then
        warn "Could not stash changes, proceeding anyway"
        stash_needed="false"
      else
        success "Changes stashed successfully"
      fi
    fi
  fi
  
  # Fetch latest from remote
  info "Fetching latest from remote..."
  if ! git fetch origin "$default_branch" 2>/dev/null; then
    warn "Could not fetch from origin/$default_branch"
  else
    success "Fetched latest from origin/$default_branch"
  fi
  
  # Create and checkout new branch from default branch
  info "Creating branch: $new_branch"
  
  if ! git checkout -b "$new_branch" "origin/$default_branch" 2>/dev/null; then
    # Fallback: create from current position
    warn "Could not branch from origin/$default_branch, trying local $default_branch"
    if ! git checkout -b "$new_branch" "$default_branch" 2>/dev/null; then
      warn "Could not branch from $default_branch, using current HEAD"
      if ! git checkout -b "$new_branch" 2>/dev/null; then
        echo -e "${RED}❌ Failed to create new branch${RESET}"
        _pr_rollback "$original_branch" "" "$default_branch" "$stash_needed"
        return 1
      fi
    fi
  fi
  success "Created and switched to branch: $new_branch"
  
  # Apply the hook modification on the new branch
  info "Applying Gitleaks hook modification..."
  
  if [ -f "$hook_file" ]; then
    if ! hook_has_gitleaks "$hook_file"; then
      debug "Appending Gitleaks snippet to existing hook..."
      
      # Backup before modification
      cp "$hook_file" "$TMP_DIR/hook_backup"
      
      if ! get_gitleaks_snippet >> "$hook_file"; then
        echo -e "${RED}❌ Failed to append Gitleaks snippet to hook${RESET}"
        _pr_rollback "$original_branch" "$new_branch" "$default_branch" "$stash_needed"
        return 1
      fi
      success "Gitleaks snippet appended to hook"
    else
      info "Hook already contains Gitleaks (on new branch)"
    fi
  else
    # Need to create the file
    debug "Creating new Husky pre-commit hook..."
    mkdir -p "$(dirname "$hook_file")"
    
    cat > "$hook_file" << 'HUSKY_HOOK_EOF'
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

HUSKY_HOOK_EOF
    
    if ! get_gitleaks_snippet >> "$hook_file"; then
      echo -e "${RED}❌ Failed to create hook with Gitleaks snippet${RESET}"
      _pr_rollback "$original_branch" "$new_branch" "$default_branch" "$stash_needed"
      return 1
    fi
    chmod +x "$hook_file"
    success "Created new Husky pre-commit hook with Gitleaks"
  fi
  
  # ==========================================
  # TEST THE HOOK BEFORE COMMITTING/PUSHING
  # ==========================================
  info "Validating the modified pre-commit hook before committing..."
  
  if ! test_hook_execution "$hook_file"; then
    echo -e "${RED}❌ Pre-commit hook validation failed!${RESET}"
    echo -e "${RED}The hook contains errors and will not be committed.${RESET}"
    _pr_rollback "$original_branch" "$new_branch" "$default_branch" "$stash_needed"
    return 1
  fi
  
  success "Pre-commit hook validation passed - safe to commit"
  
  # Stage the hook file
  info "Staging hook file: $hook_file"
  if ! git add "$hook_file"; then
    echo -e "${RED}❌ Failed to stage hook file${RESET}"
    _pr_rollback "$original_branch" "$new_branch" "$default_branch" "$stash_needed"
    return 1
  fi
  success "Hook file staged"
  
  # Check if there are actually changes to commit
  if git diff --cached --quiet 2>/dev/null; then
    info "No changes to commit (hook may already be up to date on this branch)"
    git checkout "$original_branch" 2>/dev/null || git checkout "$default_branch" 2>/dev/null || true
    git branch -D "$new_branch" 2>/dev/null || true
    if [ "$stash_needed" = "true" ]; then
      git stash pop 2>/dev/null || true
    fi
    return 0
  fi
  
  # Commit the change
  local commit_msg="Add Gitleaks secret scanning to pre-commit hook

- Integrate Gitleaks for automatic secret detection
- Block commits containing detected secrets
- Add detailed output for secret findings

Signed-off-by: Security Automation <security@automation.local>"
  
  info "Committing changes..."
  if ! git commit -m "$commit_msg" 2>&1; then
    echo -e "${RED}❌ Failed to commit changes${RESET}"
    _pr_rollback "$original_branch" "$new_branch" "$default_branch" "$stash_needed"
    return 1
  fi
  success "Changes committed successfully"
  
  # Push the branch
  info "Pushing branch to origin..."
  local push_output=""
  if ! push_output=$(git push -u origin "$new_branch" 2>&1); then
    echo -e "${RED}❌ Failed to push branch to origin${RESET}"
    echo -e "${RED}Push output: $push_output${RESET}"
    warn "Check your permissions and try again"
    _pr_rollback "$original_branch" "$new_branch" "$default_branch" "$stash_needed"
    return 1
  fi
  success "Branch pushed to origin successfully"
  
  # Create PR using GitHub CLI if available
  if check_gh_cli; then
    info "Creating Pull Request..."
    
    local pr_url=""
    if pr_url=$(gh pr create \
      --base "$default_branch" \
      --head "$new_branch" \
      --title "$PR_TITLE" \
      --body "$PR_BODY" \
      2>&1); then
      
      echo ""
      success "Pull Request created successfully!"
      echo -e "${GREEN}PR URL: ${BLUE}$pr_url${RESET}"
      PR_CREATED=true
    else
      warn "Failed to create PR via GitHub CLI: $pr_url"
      warn "Please create the PR manually: $new_branch → $default_branch"
    fi
  else
    echo ""
    warn "Please create a Pull Request manually:"
    echo -e "${YELLOW}  Branch: ${BLUE}$new_branch${RESET}"
    echo -e "${YELLOW}  Target: ${BLUE}$default_branch${RESET}"
  fi
  
  # Switch back to original branch
  info "Switching back to original branch: $original_branch"
  if ! git checkout "$original_branch" 2>/dev/null; then
    warn "Could not switch to $original_branch, trying $default_branch"
    git checkout "$default_branch" 2>/dev/null || true
  fi
  success "Switched back to original branch"
  
  # Restore stashed changes if any
  if [ "$stash_needed" = "true" ]; then
    info "Restoring stashed changes..."
    if ! git stash pop 2>/dev/null; then
      warn "Could not restore stashed changes. Use 'git stash list' to find them."
    else
      success "Stashed changes restored"
    fi
  fi
  
  echo ""
  success "PR workflow completed successfully!"
  return 0
}

# ---------- Detect pre-commit hook system ----------
detect_hook_system() {
  info "Checking for existing pre-commit hook systems..."
  
  HOOK_SYSTEM="none"
  HOOK_FILE="$GIT_HOOK_FILE"  # Default to git hooks
  
  # Check for Husky (v5+)
  if [ -d ".husky" ]; then
    info "Detected Husky directory (.husky/)"
    if [ -f "$HUSKY_HOOK_FILE" ]; then
      HOOK_SYSTEM="husky"
      HOOK_FILE="$HUSKY_HOOK_FILE"
      success "Found Husky pre-commit hook at $HUSKY_HOOK_FILE"
    else
      # Husky is installed but no pre-commit hook yet
      HOOK_SYSTEM="husky-no-hook"
      HOOK_FILE="$HUSKY_HOOK_FILE"
      warn "Husky detected but no pre-commit hook exists yet"
    fi
    return 0
  fi
  
  # Check for pre-commit (Python tool)
  if [ -f ".pre-commit-config.yaml" ] || [ -f ".pre-commit-config.yml" ]; then
    info "Detected pre-commit configuration (.pre-commit-config.yaml)"
    if [ -f "$GIT_HOOK_FILE" ]; then
      HOOK_SYSTEM="pre-commit-tool"
      HOOK_FILE="$GIT_HOOK_FILE"
      success "Found pre-commit tool hook at $GIT_HOOK_FILE"
    else
      warn "pre-commit config exists but hook not installed. Run 'pre-commit install' first, then re-run this script."
      HOOK_SYSTEM="none"
      HOOK_FILE="$GIT_HOOK_FILE"
    fi
    return 0
  fi
  
  # Check for lefthook
  if [ -f "lefthook.yml" ] || [ -f ".lefthook.yml" ] || [ -f "lefthook.yaml" ] || [ -f ".lefthook.yaml" ]; then
    info "Detected lefthook configuration"
    if [ -f "$GIT_HOOK_FILE" ]; then
      HOOK_SYSTEM="lefthook"
      HOOK_FILE="$GIT_HOOK_FILE"
      success "Found lefthook hook at $GIT_HOOK_FILE"
    else
      warn "lefthook config exists but hook not installed. Run 'lefthook install' first, then re-run this script."
      HOOK_SYSTEM="none"
      HOOK_FILE="$GIT_HOOK_FILE"
    fi
    return 0
  fi
  
  # Check for overcommit
  if [ -f ".overcommit.yml" ]; then
    info "Detected overcommit configuration (.overcommit.yml)"
    if [ -f "$GIT_HOOK_FILE" ]; then
      HOOK_SYSTEM="overcommit"
      HOOK_FILE="$GIT_HOOK_FILE"
      success "Found overcommit hook at $GIT_HOOK_FILE"
    else
      HOOK_SYSTEM="none"
      HOOK_FILE="$GIT_HOOK_FILE"
    fi
    return 0
  fi
  
  # Check for simple-git-hooks
  if [ -f ".simple-git-hooks.json" ] || [ -f "simple-git-hooks.json" ]; then
    info "Detected simple-git-hooks configuration"
    if [ -f "$GIT_HOOK_FILE" ]; then
      HOOK_SYSTEM="simple-git-hooks"
      HOOK_FILE="$GIT_HOOK_FILE"
      success "Found simple-git-hooks hook at $GIT_HOOK_FILE"
    else
      HOOK_SYSTEM="none"
      HOOK_FILE="$GIT_HOOK_FILE"
    fi
    return 0
  fi
  
  # Check package.json for hook configurations
  if [ -f "package.json" ]; then
    if grep -q '"husky"' package.json 2>/dev/null; then
      info "Detected Husky configuration in package.json"
      if [ -f "$GIT_HOOK_FILE" ]; then
        HOOK_SYSTEM="husky-legacy"
        HOOK_FILE="$GIT_HOOK_FILE"
        success "Found Husky (legacy) hook at $GIT_HOOK_FILE"
        return 0
      fi
    fi
    if grep -q '"simple-git-hooks"' package.json 2>/dev/null; then
      info "Detected simple-git-hooks in package.json"
      if [ -f "$GIT_HOOK_FILE" ]; then
        HOOK_SYSTEM="simple-git-hooks"
        HOOK_FILE="$GIT_HOOK_FILE"
        success "Found simple-git-hooks hook at $GIT_HOOK_FILE"
        return 0
      fi
    fi
  fi
  
  # Check for existing .git/hooks/pre-commit (custom hook)
  if [ -f "$GIT_HOOK_FILE" ]; then
    # Check if it's a sample hook (usually disabled)
    if grep -q "^# This hook" "$GIT_HOOK_FILE" 2>/dev/null && ! [ -x "$GIT_HOOK_FILE" ]; then
      info "Found sample pre-commit hook (disabled)"
      HOOK_SYSTEM="none"
      HOOK_FILE="$GIT_HOOK_FILE"
    else
      HOOK_SYSTEM="custom"
      HOOK_FILE="$GIT_HOOK_FILE"
      success "Found custom pre-commit hook at $GIT_HOOK_FILE"
    fi
    return 0
  fi
  
  info "No existing pre-commit hook system detected"
  HOOK_SYSTEM="none"
  HOOK_FILE="$GIT_HOOK_FILE"
  return 0
}

# ---------- Gitleaks hook snippet (for appending to existing hooks) ----------
# Note: This snippet is designed to be POSIX-compatible for sh hooks
get_gitleaks_snippet() {
  cat << 'GITLEAKS_SNIPPET_EOF'

# >>>>>> GITLEAKS SECRET SCAN - DO NOT REMOVE >>>>>>
# Gitleaks secret scanning - automatically appended by setup-pre-commit-hook.sh

_gitleaks_scan() {
  _GL_RED='\033[0;31m'
  _GL_GREEN='\033[1;32m'
  _GL_YELLOW='\033[1;33m'
  _GL_RESET='\033[0m'

  _GL_GITLEAKS_BIN=".gitleaks/bin/gitleaks"

  if [ ! -x "$_GL_GITLEAKS_BIN" ]; then
    echo "${_GL_RED}❌ Gitleaks binary not found at $_GL_GITLEAKS_BIN${_GL_RESET}"
    echo "${_GL_YELLOW}Run the setup script again to install Gitleaks${_GL_RESET}"
    return 1
  fi

  _GL_STAGED_FILES="$(git diff --cached --name-only --diff-filter=ACMR)"
  if [ -z "$_GL_STAGED_FILES" ]; then
    echo "${_GL_GREEN}✔ Gitleaks: No staged files to scan${_GL_RESET}"
    return 0
  fi

  # Run gitleaks
  _GL_RAW_OUTPUT=""
  _GL_SCAN_EXIT=0
  
  if [ -f ".gitleaksignore" ]; then
    echo "${_GL_YELLOW}ℹ Using .gitleaksignore${_GL_RESET}"
    _GL_RAW_OUTPUT="$("$_GL_GITLEAKS_BIN" protect --staged -v --gitleaks-ignore-path=.gitleaksignore 2>&1)" || _GL_SCAN_EXIT=$?
  else
    _GL_RAW_OUTPUT="$("$_GL_GITLEAKS_BIN" protect --staged -v 2>&1)" || _GL_SCAN_EXIT=$?
  fi

  if [ "$_GL_SCAN_EXIT" -gt 1 ]; then
    echo "${_GL_RED}❌ Gitleaks execution error:${_GL_RESET}"
    echo "$_GL_RAW_OUTPUT"
    return 1
  fi

  if [ "$_GL_SCAN_EXIT" -eq 1 ]; then
    echo "${_GL_RED}❌ SECRETS DETECTED BY GITLEAKS${_GL_RESET}"
    echo "──────────────────── DETAILS ────────────────────"
    echo "$_GL_RAW_OUTPUT"
    echo "─────────────────────────────────────────────────"
    echo "${_GL_RED}❌ PRE-COMMIT BLOCKED: Remove or rotate secrets before committing${_GL_RESET}"
    return 1
  fi

  echo "${_GL_GREEN}✅ Gitleaks: Secret scan passed${_GL_RESET}"
  return 0
}

# Run Gitleaks scan
if ! _gitleaks_scan; then
  exit 1
fi
# <<<<<< GITLEAKS SECRET SCAN - DO NOT REMOVE <<<<<<
GITLEAKS_SNIPPET_EOF
}

# ---------- Check if Gitleaks is already in hook ----------
hook_has_gitleaks() {
  local hook_file="$1"
  if [ -f "$hook_file" ]; then
    if grep -q "$GITLEAKS_START_MARKER" "$hook_file" 2>/dev/null; then
      return 0
    fi
    # Also check for old-style gitleaks detection
    if grep -q "GITLEAKS_BIN=.*gitleaks" "$hook_file" 2>/dev/null; then
      return 0
    fi
    # Check for new-style variable name
    if grep -q "_GL_GITLEAKS_BIN=.*gitleaks" "$hook_file" 2>/dev/null; then
      return 0
    fi
  fi
  return 1
}

# ---------- Create standalone hook (no existing hook system) ----------
create_standalone_hook() {
  info "Creating standalone pre-commit hook at $GIT_HOOK_FILE"
  
  cat > "$GIT_HOOK_FILE" << 'STANDALONE_EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RESET='\033[0m'

fail() {
  echo -e "${RED}❌ PRE-COMMIT BLOCKED${RESET}"
  echo -e "${RED}$1${RESET}"
  exit 1
}

GITLEAKS_BIN=".gitleaks/bin/gitleaks"

if [ ! -x "$GITLEAKS_BIN" ]; then
  fail "Gitleaks binary not found at $GITLEAKS_BIN\nRun the setup script again to install Gitleaks"
fi

STAGED_FILES="$(git diff --cached --name-only --diff-filter=ACMR)"
if [ -z "$STAGED_FILES" ]; then
  echo -e "${GREEN}✔ No staged files to scan${RESET}"
  exit 0
fi

# Optional .gitleaksignore
IGNORE_ARGS=()
if [ -f ".gitleaksignore" ]; then
  IGNORE_ARGS+=(--gitleaks-ignore-path=.gitleaksignore)
  echo -e "${YELLOW}ℹ Using .gitleaksignore${RESET}"
fi

set +e
# Use parameter expansion to safely handle empty array with set -u
RAW_OUTPUT="$("$GITLEAKS_BIN" protect --staged -v ${IGNORE_ARGS[@]+"${IGNORE_ARGS[@]}"} 2>&1)"
SCAN_EXIT=$?
set -e

if [ "$SCAN_EXIT" -gt 1 ]; then
  fail "Gitleaks execution error:\n$RAW_OUTPUT"
fi

if [ "$SCAN_EXIT" -eq 1 ]; then
  echo -e "${RED}❌ SECRETS DETECTED${RESET}"
  echo "──────────────────── DETAILS ────────────────────"

  # Pretty-print output line by line with colors using shell parameter expansion
  echo "$RAW_OUTPUT" | while IFS=: read -r file rest; do
    echo -e "${YELLOW}${file}${RESET}:${RED}${rest}${RESET}"
  done

  echo "─────────────────────────────────────────────────"
  fail "Remove or rotate secrets before committing"
fi

echo -e "${GREEN}✅ Secret scan passed${RESET}"
exit 0
STANDALONE_EOF

  chmod +x "$GIT_HOOK_FILE"
  success "Standalone pre-commit hook installed at $GIT_HOOK_FILE"
}

# ---------- Fetch latest version ----------
info "Fetching latest Gitleaks version from GitHub..."

LATEST_VERSION=""
if ! LATEST_VERSION="$(curl -fsSL https://api.github.com/repos/gitleaks/gitleaks/releases/latest 2>/dev/null | grep '"tag_name"' | head -n1 | cut -d'"' -f4)"; then
  fail "Unable to reach GitHub API to fetch Gitleaks version"
fi

if [ -z "$LATEST_VERSION" ]; then
  fail "Empty Gitleaks version received from GitHub API"
fi

info "Latest Gitleaks version: $LATEST_VERSION"

CACHED_VERSION=""
if [ -f "$VERSION_FILE" ]; then
  CACHED_VERSION="$(cat "$VERSION_FILE" 2>/dev/null || echo "")"
fi

# ---------- Install or update Gitleaks ----------
if [ ! -x "$GITLEAKS_BIN" ] || [ "$CACHED_VERSION" != "$LATEST_VERSION" ]; then
  echo -e "${YELLOW}📥 Installing or updating Gitleaks...${RESET}"

  if [ -x "$GITLEAKS_BIN" ]; then
    echo -e "${YELLOW}ℹ New Gitleaks version detected: ${CACHED_VERSION} → ${LATEST_VERSION}${RESET}"
  else
    echo -e "${YELLOW}ℹ Gitleaks not found locally. Installing version ${LATEST_VERSION}${RESET}"
  fi

  ASSET="gitleaks_${LATEST_VERSION#v}_${OS}_${ARCH}.tar.gz"
  URL="https://github.com/gitleaks/gitleaks/releases/download/${LATEST_VERSION}/${ASSET}"
  TMP="$TMP_DIR/$ASSET"

  info "Downloading from: $URL"
  if ! curl -fsSL "$URL" -o "$TMP" 2>/dev/null; then
    fail "Failed to download Gitleaks binary from $URL"
  fi
  
  info "Extracting to: $GITLEAKS_BIN_DIR"
  if ! tar -xzf "$TMP" -C "$GITLEAKS_BIN_DIR" 2>/dev/null; then
    fail "Failed to extract Gitleaks archive"
  fi
  
  if ! chmod +x "$GITLEAKS_BIN"; then
    fail "Failed to make Gitleaks executable"
  fi
  
  echo "$LATEST_VERSION" > "$VERSION_FILE"

  echo -e "${GREEN}✅ Gitleaks ${LATEST_VERSION} installed${RESET}"
else
  echo -e "${GREEN}✔ Gitleaks is up-to-date (version ${CACHED_VERSION})${RESET}"
fi

# ---------- Validate binary ----------
info "Validating Gitleaks binary..."
if ! "$GITLEAKS_BIN" version >/dev/null 2>&1; then
  fail "Gitleaks binary is not executable or corrupted"
fi
success "Gitleaks binary validated successfully"

# ---------- Detect hook system and install/append Gitleaks ----------
detect_hook_system

echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${YELLOW}  Pre-commit Hook Configuration${RESET}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"

case "$HOOK_SYSTEM" in
  husky|husky-no-hook)
    # Codebase-level hook - needs to be committed via PR
    info "Hook system detected: $HOOK_SYSTEM (codebase-level)"
    info "Hook file location: $HOOK_FILE"
    
    if hook_has_gitleaks "$HOOK_FILE"; then
      success "Gitleaks secret scanning is already configured in $HOOK_FILE"
      info "No changes needed - hook is up to date"
    else
      if [ "$HOOK_SYSTEM" = "husky" ]; then
        info "Will append Gitleaks secret scanning to existing Husky hook"
        HOOK_MODIFIED=true
        NEEDS_PR=true
      else
        # husky-no-hook - need to create new file
        info "Will create new Husky pre-commit hook with Gitleaks"
        HOOK_MODIFIED=true
        NEEDS_PR=true
      fi
    fi
    ;;
    
  husky-legacy|pre-commit-tool|lefthook|overcommit|simple-git-hooks|custom)
    # Git hooks directory - local only, not committed
    info "Hook system detected: $HOOK_SYSTEM (local .git/hooks)"
    info "Hook file location: $HOOK_FILE"
    info "This hook type is local-only and will not be committed"
    
    if hook_has_gitleaks "$HOOK_FILE"; then
      success "Gitleaks secret scanning is already configured in $HOOK_FILE"
    else
      info "Appending Gitleaks secret scanning to existing hook..."
      
      # Backup existing hook
      BACKUP_FILE="${HOOK_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
      if ! cp "$HOOK_FILE" "$BACKUP_FILE"; then
        fail "Failed to create backup of existing hook"
      fi
      info "Created backup: $BACKUP_FILE"
      
      # Append Gitleaks snippet
      if ! get_gitleaks_snippet >> "$HOOK_FILE"; then
        warn "Failed to append Gitleaks snippet, restoring from backup..."
        cp "$BACKUP_FILE" "$HOOK_FILE"
        fail "Failed to add Gitleaks to pre-commit hook"
      fi
      
      # Test the modified hook
      if test_hook_execution "$HOOK_FILE"; then
        success "Gitleaks secret scanning appended to $HOOK_FILE"
        info "Your existing hook logic has been preserved"
      else
        warn "Hook validation failed, restoring from backup..."
        cp "$BACKUP_FILE" "$HOOK_FILE"
        fail "Failed to add Gitleaks to pre-commit hook. Please check the hook file manually."
      fi
    fi
    ;;
    
  none)
    # No hook system - create standalone local hook
    info "No existing pre-commit hook system detected"
    info "Creating local standalone hook (not committed to repo)"
    
    # Check if a hook file exists (might be sample or non-executable)
    if [ -f "$GIT_HOOK_FILE" ]; then
      if hook_has_gitleaks "$GIT_HOOK_FILE"; then
        success "Pre-commit hook with Gitleaks already exists at $GIT_HOOK_FILE"
      else
        # There's a file but it's not a working hook (e.g., sample)
        # Back it up and create new
        BACKUP_FILE="${GIT_HOOK_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
        if ! mv "$GIT_HOOK_FILE" "$BACKUP_FILE"; then
          fail "Failed to backup existing hook file"
        fi
        info "Moved existing sample/inactive hook to: $BACKUP_FILE"
        create_standalone_hook
        
        # Test the new hook
        if ! test_hook_execution "$GIT_HOOK_FILE"; then
          warn "Hook validation failed, restoring from backup..."
          mv "$BACKUP_FILE" "$GIT_HOOK_FILE"
          fail "Failed to create pre-commit hook. Please check manually."
        fi
      fi
    else
      create_standalone_hook
      
      # Test the new hook
      if ! test_hook_execution "$GIT_HOOK_FILE"; then
        rm -f "$GIT_HOOK_FILE"
        fail "Failed to create valid pre-commit hook. Please check manually."
      fi
    fi
    ;;
    
  *)
    fail "Unknown hook system: $HOOK_SYSTEM"
    ;;
esac

# ---------- Handle PR creation for codebase-level hooks ----------
if [ "$NEEDS_PR" = true ] && [ "$HOOK_MODIFIED" = true ]; then
  if ! create_pr_for_hook_change "$HOOK_FILE"; then
    echo ""
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${RED}  PR Creation Failed${RESET}"
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
    warn "The PR workflow encountered an error."
    warn "Please manually create a branch, add the Gitleaks hook, and create a PR."
    echo ""
    echo -e "${YELLOW}To manually add Gitleaks to your Husky hook:${RESET}"
    echo -e "${BLUE}  1. Create a new branch from your default branch${RESET}"
    echo -e "${BLUE}  2. Run this script again on that branch${RESET}"
    echo -e "${BLUE}  3. Commit and push the changes${RESET}"
    echo -e "${BLUE}  4. Create a PR to merge into your default branch${RESET}"
    exit 1
  fi
fi

echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN}🎉 Setup complete!${RESET}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo -e "${GREEN}Pre-commit hook will run Gitleaks automatically on commits.${RESET}"
echo -e "${BLUE}Hook location: ${HOOK_FILE:-$GIT_HOOK_FILE}${RESET}"
echo -e "${BLUE}Gitleaks version: ${LATEST_VERSION}${RESET}"
echo ""

if is_codebase_level_hook "$HOOK_SYSTEM"; then
  if [ "$NEEDS_PR" = true ]; then
    if [ "$PR_CREATED" = true ]; then
      echo -e "${MAGENTA}✅ A PR has been created to add Gitleaks to your codebase-level hook.${RESET}"
      echo -e "${MAGENTA}   Once merged, all team members will have Gitleaks scanning enabled.${RESET}"
    else
      echo -e "${YELLOW}⚠ Changes have been pushed but PR was not created automatically.${RESET}"
      echo -e "${YELLOW}   Please create a PR manually to merge the changes.${RESET}"
    fi
  else
    echo -e "${GREEN}Note: Your codebase-level hook already includes Gitleaks scanning.${RESET}"
  fi
else
  if [ "$HOOK_SYSTEM" != "none" ]; then
    echo -e "${YELLOW}Note: Your existing $HOOK_SYSTEM hooks are preserved and will run first.${RESET}"
    echo -e "${YELLOW}Gitleaks scan has been appended to run after your existing checks.${RESET}"
  fi
  echo -e "${YELLOW}Note: This hook is local to your machine (.git/hooks) and is not committed.${RESET}"
  echo -e "${YELLOW}Each developer needs to run this setup script after cloning.${RESET}"
fi
