name: Code Review Automation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify-reviewers:
    # Skip notification if PR is a draft
    if: github.event.pull_request.draft == false  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch User Mapping from GitHub-Teams repository
        run: |
          USER_MAPPING=$(curl -s -H "Authorization: token ${{ secrets.JOSYS_TOKEN }}" https://api.github.com/repos/josys-src/GitHub-Teams/contents/.github/user.json | jq -r '.content' | base64 --decode )
          echo "$USER_MAPPING" > user_mapping.json

      - name: Set up Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install shyaml jq

      - name: Extract Requested Reviewers
        id: extract_reviewers
        run: |
          source venv/bin/activate
          reviewers=$(jq -r '.pull_request.requested_reviewers | .[] | .login' "$GITHUB_EVENT_PATH" | tr '\n' ' ')
          echo "reviewers=${reviewers}" >> $GITHUB_ENV

      - name: Extract Emails for Reviewers
        id: user_mapping
        run: |
          source venv/bin/activate
          email_ids=""
          IFS=' ' read -r -a owners <<< "${{ env.reviewers }}"
          for owner in "${owners[@]}"; do
            email_id=$(jq -r --arg owner "$owner" '.[$owner]' user_mapping.json)
            echo "Email ID for $owner: $email_id"
            if [ -n "$email_id" ]; then
              email_ids="$email_ids $email_id"
            fi
          done
          echo "email_ids=$email_ids" >> $GITHUB_ENV

      - name: Retrieve Slack IDs from Emails
        id: slack_ids
        run: |
          source venv/bin/activate
          slack_ids=""
          IFS=' ' read -r -a emails <<< "${{ env.email_ids }}"

          for email in "${emails[@]}"; do
            slack_id=$(curl --request GET \
            --url "${{secrets.SLACK_EMAIL_LOOKUP_API}}?email=$email" \
            --header "Authorization: Bearer ${{ secrets.SLACK_API_CO_TOKEN }}" \
            --header 'Content-Type: application/x-www-form-urlencoded' | jq -r '.user.id')
            if [ -n "$slack_id" ] && [ "$slack_id" != "null" ]; then
              slack_ids="$slack_ids <@$slack_id>"
            fi
          done
          echo "slack_ids=$slack_ids" >> $GITHUB_ENV

      - name: Extract PR Author
        id: pr_author
        run: |
          source venv/bin/activate
          author_login=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
          echo "author_login=${author_login}" >> $GITHUB_ENV

      - name: Get Slack ID of PR Author
        id: author_slack_id
        run: |
          source venv/bin/activate
          author_email=$(jq -r --arg author "${{ env.author_login }}" '.[$author]' user_mapping.json)
          author_slack_id=$(curl --request GET \
            --url "${{secrets.SLACK_EMAIL_LOOKUP_API}}?email=$author_email" \
            --header "Authorization: Bearer ${{ secrets.SLACK_API_CO_TOKEN }}" \
            --header 'Content-Type: application/x-www-form-urlencoded' | jq -r '.user.id')
          if [ -n "$author_slack_id" ] && [ "$author_slack_id" != "null" ]; then
            author_slack_id="<@$author_slack_id>"
          else
            author_slack_id="${{ env.author_login }}"
          fi
          echo "author_slack_id=${author_slack_id}" >> $GITHUB_ENV

      - name: Notify Code Owners
        run: |
          source venv/bin/activate
          EVENT_TYPE="${{ github.event.action }}"

          MESSAGE=":bell: *Code Review Request*\n"
          MESSAGE+="*Repository:* ${{ github.repository }}\n"
          MESSAGE+="*Branch:* ${{ github.event.pull_request.base.ref }} <-- ${{ github.event.pull_request.head.ref }}\n"
          MESSAGE+="*PR:* #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}\n"
          MESSAGE+="*URL:* ${{ github.event.pull_request.html_url }}\n"
          MESSAGE+="*Event Type:*  $EVENT_TYPE \n"
          MESSAGE+="*Author:* ${{ env.author_slack_id }}\n"
          MESSAGE+="*Reviewers:* ${{ env.slack_ids }}"

          if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]] || [[ "${{ github.event.pull_request.base.ref }}" == "staging" ]] || [[ "${{ github.event.pull_request.base.ref }}" == "production" ]]; then
            WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_CO_URL }}"
          elif [[ "${{ github.event.pull_request.base.ref }}" == "release"* ]]; then
            WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_CO_RB_API }}"
          else
            WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_CO_QB_URL }}"
          fi

          # Send the message to Slack
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$MESSAGE\"}" $WEBHOOK_URL
