name: Security Check Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created, edited]

jobs:
  extract-base-branch:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      base_branch: ${{ steps.extract.outputs.branch }}
    steps:
      - name: Extract Base Branch
        id: extract
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "branch=${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch=main" >> $GITHUB_OUTPUT
          fi

  dependency-scan:
    if: github.event_name == 'pull_request'
    needs: extract-base-branch
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      security-events: write
    continue-on-error: true
    steps:
      - uses: josys-src/security_template/actions/dependency-scanning@main
        with:
          environment: ${{ needs.extract-base-branch.outputs.base_branch }}
          JOSYS_SECURITY_AWS_ROLE: ${{ secrets.JOSYS_SECURITY_AWS_ROLE }}
          JOSYS_SECURITY_AWS_REGION: ${{ secrets.JOSYS_SECURITY_AWS_REGION }}
          JOSYS_SECURITY_S3_BUCKET_NAME: ${{ secrets.JOSYS_SECURITY_S3_BUCKET_NAME }}
          JOSYS_SECURITY_S3_FILE_KEY: ${{ secrets.JOSYS_SECURITY_S3_FILE_KEY }}
          JOSYS_DEV_SECURITY_AWS_ROLE: ${{ secrets.JOSYS_DEV_SECURITY_AWS_ROLE }}
          JOSYS_DEV_SECURITY_AWS_REGION: ${{ secrets.JOSYS_DEV_SECURITY_AWS_REGION }}
          JOSYS_DEV_SECURITY_S3_BUCKET_NAME: ${{ secrets.JOSYS_DEV_SECURITY_S3_BUCKET_NAME }}
          JOSYS_DEV_SECURITY_S3_FILE_KEY: ${{ secrets.JOSYS_DEV_SECURITY_S3_FILE_KEY }}
          NPM_AUTH_READ_TOKEN: ${{ secrets.NPM_AUTH_READ_TOKEN }}
          GH_SECURITY_TOKEN: ${{ secrets.GH_SECURITY_TOKEN }}

  secret-scan:
    if: always() && github.event_name == 'pull_request'
    needs: dependency-scan
    runs-on: ubuntu-latest
    steps:
      - uses: josys-src/security_template/actions/secret-scanning@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  sbom-generate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: josys-src/security_template/actions/sbom-generation@main

  sast-scan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: josys-src/security_template/actions/sast-scanning@main
        with:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  manual-scan-approval:
    
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Print GitHub Event
        shell: bash
        run: |
          echo "Event Payload:"
          cat $GITHUB_EVENT_PATH
      - name: Run Security Approval Check
        uses: josys-src/security_template/actions/security-approval@main
        with:
          security_token: ${{ secrets.GH_SECURITY_TOKEN }}